# Generated by Django 5.2 on 2025-12-07 09:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(help_text='Name of donating organization or individual', max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number')])),
                ('location', models.CharField(help_text='City or general location (for privacy)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
                'ordering': ['organization_name'],
            },
        ),
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(help_text='Name of pantry organization', max_length=100)),
                ('capacity', models.PositiveIntegerField(help_text='Approximate weekly capacity (number of families served)')),
                ('location', models.CharField(help_text='City or general location', max_length=100)),
                ('service_area', models.CharField(help_text='Geographic area served by this pantry', max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pantry',
                'verbose_name_plural': 'Pantries',
                'ordering': ['organization_name'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('produce', 'Fresh Produce'), ('dairy', 'Dairy Products'), ('meat', 'Meat & Protein'), ('bakery', 'Bakery Items'), ('canned', 'Canned Goods'), ('frozen', 'Frozen Foods'), ('pantry', 'Pantry Staples'), ('prepared', 'Prepared Meals'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the food items')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity (lbs, count, servings, etc.)', max_digits=8)),
                ('unit', models.CharField(default='lbs', help_text='Unit of measurement (lbs, servings, boxes, etc.)', max_length=20)),
                ('location', models.CharField(help_text='Pickup location (city level for privacy)', max_length=100)),
                ('expiry_date', models.DateTimeField(help_text='When this food expires')),
                ('pickup_instructions', models.TextField(blank=True, help_text='Special instructions for pickup')),
                ('status', models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('expired', 'Expired'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donor')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_donations', to='donations.pantry')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expiry_date'], name='donations_d_status_b53369_idx'), models.Index(fields=['location'], name='donations_d_locatio_8a249f_idx'), models.Index(fields=['food_type'], name='donations_d_food_ty_62578c_idx'), models.Index(fields=['created_at'], name='donations_d_created_26bd74_idx')],
            },
        ),
    ]
