# Generated by Django 5.2 on 2025-12-07 15:40

import donations.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_d_locatio_8a249f_idx',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_d_food_ty_62578c_idx',
        ),
        migrations.AddField(
            model_name='donation',
            name='fulfillment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='business_hours',
            field=models.TextField(blank=True, help_text='Hours when donations can be picked up'),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='organization_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('grocery', 'Grocery Store'), ('bakery', 'Bakery'), ('farm', 'Farm'), ('caterer', 'Catering Service'), ('event', 'Event Organizer'), ('individual', 'Individual'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pantry',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pantry',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pantry',
            name='organization_type',
            field=models.CharField(choices=[('food_bank', 'Food Bank'), ('soup_kitchen', 'Soup Kitchen'), ('shelter', 'Homeless Shelter'), ('community_center', 'Community Center'), ('church', 'Religious Organization'), ('school', 'School'), ('nonprofit', 'Nonprofit Organization'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='pantry',
            name='pickup_hours',
            field=models.TextField(blank=True, help_text='Hours when donations can be picked up'),
        ),
        migrations.AddField(
            model_name='pantry',
            name='storage_types',
            field=models.JSONField(default=list, help_text='Types of storage available'),
        ),
        migrations.AddField(
            model_name='pantry',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='expiry_date',
            field=models.DateTimeField(help_text='When this food expires', validators=[donations.validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='food_type',
            field=models.CharField(choices=[('produce', 'Fresh Produce'), ('dairy', 'Dairy Products'), ('bread', 'Bread & Baked Goods'), ('canned', 'Canned Goods'), ('frozen', 'Frozen Items'), ('meat', 'Meat & Poultry'), ('pantry', 'Pantry Staples'), ('prepared', 'Prepared Meals'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity (lbs, count, servings, etc.)', max_digits=8, validators=[donations.validators.validate_positive_quantity]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[donations.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='location',
            field=models.CharField(help_text='City or general location (for privacy)', max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='organization_name',
            field=models.CharField(help_text='Name of donating organization or individual', max_length=255),
        ),
        migrations.AlterField(
            model_name='pantry',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Maximum items that can be handled'),
        ),
        migrations.AlterField(
            model_name='pantry',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, validators=[donations.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='pantry',
            name='location',
            field=models.CharField(help_text='City or general location', max_length=255),
        ),
        migrations.AlterField(
            model_name='pantry',
            name='organization_name',
            field=models.CharField(help_text='Name of pantry organization', max_length=255),
        ),
        migrations.AlterField(
            model_name='pantry',
            name='service_area',
            field=models.CharField(help_text='Geographic area served by this pantry', max_length=255),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['location', 'status'], name='donations_d_locatio_f28cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['food_type', 'status'], name='donations_d_food_ty_4ddc44_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['location', 'is_verified'], name='donations_d_locatio_5ddc47_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['organization_type'], name='donations_d_organiz_a3109f_idx'),
        ),
        migrations.AddIndex(
            model_name='pantry',
            index=models.Index(fields=['location', 'service_area'], name='donations_p_locatio_25a851_idx'),
        ),
        migrations.AddIndex(
            model_name='pantry',
            index=models.Index(fields=['organization_type'], name='donations_p_organiz_5c51c4_idx'),
        ),
    ]
